[project]
name = "cmeel-console-bridge"
version = "1.0.2"
description = "cmeel distribution for console-bridge, A ROS-independent package for logging that seamlessly pipes into rosconsole/rosout for ROS-dependent packages."
readme = "console_bridge/README.md"
requires-python = ">= 3.7"
license = "Zlib"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-console-bridge"

[build-system]
requires = ["cmeel[build]"]
build-backend = "cmeel.build"
source = "console_bridge"
# ref. https://github.com/ros/console_bridge/pull/97
run-tests = false
